---
  #all server, apt update
  - hosts: all
    become: yes
    vars:
      ansible_python_interpreter: /usr/bin/python3

    tasks:
      - name: Check postgresql-13 software is installed
        package_facts:
          manager: "apt"
#certain package info

      - name: Postgresql & Vim package status
        debug:
          msg: "{{ ansible_facts.packages[item] }} {{ 'installed' if item in ansible_facts.packages else 'not installed' }}"
      #just installed package list version
        loop:
        - vim
        - postgresql-13
        - net-tools
        - dstat
