---
  - hosts: postgre
    become: yes
    vars:
      ansible_python_interpreter: /usr/bin/python3

    tasks:
      - name: Postgresql Service restart
        become: yes
        ansible.builtin.service:
          name: postgresql
          state: restarted
