---
  #create postgresql db for master
  - hosts: master
    become: yes
    vars:
      ansible_python_interpreter: /usr/bin/python3

    tasks:
      - name: File Create for regexp line postgresql conf file
        ansible.builtin.lineinfile:
          path: /etc/postgresql/13/main/postgresql.conf
          regexp: "#listen_addresses = 'localhost'"
          line: listen_addresses = '*'
